#!/bin/bash 

#Powderday cluster setup convenience script for Torque queue mananger
#on Fock at Haverford College.  This sets up the model files for a
#cosmological simulation where we want to model many galaxies at once.

#Notes of interest:

#1. This does *not* set up the parameters_master.py file: it is
#assumed that you will *very carefully* set this up yourself.

#2. This requires bash versions >= 3.0.  To check, type at the shell
#prompt: 

#> echo $BASH_VERSION

n_nodes=$1
model_dir=$2
hydro_dir=$3
model_run_name=$4
COSMOFLAG=$5
model_dir_remote=$6
hydro_dir_remote=$7
xpos=$8
ypos=$9
zpos=${10}
halo=${11}
snap=${12}
nhalos=${13}

echo "processing model file for halo,snapshot:  $halo,$snap"


#clear the pyc files
rm -f *.pyc

#set up the model_**.py file

filem="$model_dir/halo${halo}_snap${snap}.py"
echo "writing to $filem"
rm -f $filem


echo "#Snapshot Parameters" >> $filem
echo "#<Parameter File Auto-Generated by setup_all_cluster.sh>" >> $filem
echo "snapshot_num =  $snap" >> $filem
echo -e "\n" >> $filem

echo "if snapshot_num < 10:" >> $filem
echo -e "\t snapnum_str = '00'+str(snapshot_num)" >> $filem
echo -e "elif snapshot_num >= 10 and snapshot_num <100:" >> $filem
echo -e "\t snapnum_str = '0'+str(snapshot_num)" >> $filem
echo -e "else:" >> $filem
echo -e "\t snapnum_str = str(snapshot_num)" >> $filem

echo -e "\n" >>$filem

if [ $COSMOFLAG -eq 1 ]
then
    echo "hydro_dir = '$hydro_dir_remote/snapdir_'+snapnum_str+'/'">>$filem
    echo "snapshot_name = 'snapshot_'+snapnum_str+'.0.hdf5'" >>$filem
else
    echo "hydro_dir = '$hydro_dir_remote/'">>$filem
    echo "snapshot_name = 'snapshot_'+snapnum_str+'.hdf5'" >>$filem
fi


echo -e "\n" >>$filem

echo "#where the files should go" >>$filem
echo "PD_output_dir = '${model_dir_remote}/' ">>$filem
echo "Auto_TF_file = 'snap'+snapnum_str+'.logical' ">>$filem
echo "Auto_dustdens_file = 'snap'+snapnum_str+'.dustdens' ">>$filem

echo -e "\n\n" >>$filem
echo "#===============================================" >>$filem
echo "#FILE I/O" >>$filem
echo "#===============================================" >>$filem
echo "inputfile = PD_output_dir+'/halo${halo}.snap'+snapnum_str+'.rtin'" >>$filem
echo "outputfile = PD_output_dir+'/halo${halo}.snap'+snapnum_str+'.rtout'" >>$filem

echo -e "\n\n" >>$filem
echo "#===============================================" >>$filem
echo "#GRID POSITIONS" >>$filem
echo "#===============================================" >>$filem
echo "x_cent = ${xpos}" >>$filem
echo "y_cent = ${ypos}" >>$filem
echo "z_cent = ${zpos}" >>$filem




echo "writing qsub file"
qsubfile="$model_dir/qsub_master.snap"${snap}".qsub"
rm -f $qsubfile
echo $qsubfile

echo "#! /bin/bash" >>$qsubfile
echo "#PBS -N $model_run_name.snap${snap}" >>$qsubfile
echo "#PBS -l nodes=$n_nodes" >>$qsubfile
echo "#PBS -m bea" >>$qsubfile
echo "#PBS -M dnarayan@haverford.edu" >>$qsubfile

echo -e "\n" >>$qsubfile
echo "cd /home/desika/pd" >>$qsubfile

    
for (( i=0; i<=$nhalos; i++ ))
do
    
    echo "python pd_front_end.py $model_dir_remote parameters_master halo${i}_snap${snap}  > $model_dir_remote/halo${i}_snap${snap}.txt">>$qsubfile
	
     

done

