#!/bin/bash
#SBATCH --job-name=pd_test
#SBATCH --output=pd.o
#SBATCH --error=pd.e
#SBATCH --mail-type=ALL
#SBATCH --mail-user=desika.narayanan@gmail.com
#SBATCH --time=240:00:00
#SBATCH --ntasks=32
#SBATCH --mem-per-cpu=3800
#SBATCH --account=narayanan
#SBATCH --qos=narayanan-b
###SBATCH --constraint=c34


module purge
module load git/1.9.0 
module load gsl/1.16
module load gcc/5.2.0
module load hdf5/1.8.16
module load openmpi/1.10.2
python /home/desika.narayanan/pd/pd_front_end.py /home/desika.narayanan/pd/examples/gadget parameters_master parameters_model > LOG
