#!/bin/bash 

#Powderday cluster setup convenience script for SLURM queue mananger
#on HiPerGator at the University of FLorida

#Notes of interest:

#1. This does *not* set up the parameters_master.py file: it is
#assumed that you will *very carefully* set this up yourself.

#2. This requires bash versions >= 3.0.  To check, type at the shell
#prompt: 

#> echo $BASH_VERSION

n_nodes=$1
startsnap=$2
endsnap=$3
model_dir=$4
hydro_dir=$5
model_run_name=$6
COSMOFLAG=$7
FILTERFLAG=$8
model_dir_remote=$9
hydro_dir_remote=$10

for (( i=$startsnap; i<=$endsnap; i++ ))


do

    echo "processing model file for snapshot:  $i"


    #clear the pyc files
    rm -f *.pyc

    #set up the model_**.py file

    filem="$model_dir/model_$i.py"
    rm -f $filem
    
    echo "#Snapshot Parameters" >> $filem
    echo "#<Parameter File Auto-Generated by setup_all_cluster.sh>" >> $filem
    echo "snapshot_num =  $i" >> $filem
    echo -e "\n" >> $filem
    
    echo "if snapshot_num < 10:" >> $filem
    echo -e "\t snapnum_str = '00'+str(snapshot_num)" >> $filem
    echo -e "elif snapshot_num >= 10 and snapshot_num <100:" >> $filem
    echo -e "\t snapnum_str = '0'+str(snapshot_num)" >> $filem
    echo -e "else:" >> $filem
    echo -e "\t snapnum_str = str(snapshot_num)" >> $filem
 
    echo -e "\n" >>$filem
    
    if [ $COSMOFLAG -eq 1 ]
    then
	echo "hydro_dir = '$hydro_dir_remote/snapdir_'+snapnum_str+'/'">>$filem
	echo "snapshot_name = 'snapshot_'+snapnum_str+'.0.hdf5'" >>$filem
    elif [ $FILTERFLAG -eq 1]
    then 
        echo "hydro_dir = '$hydro_dir_remote/snapdir_'+snapnum_str+'/'">>$filem
	echo "snapshot_name = 'snap_'+snapnum_str+'_galaxy'+galaxy_num_str+'.filtered.hdf5'">>$filem
    else
	echo "hydro_dir = '$hydro_dir_remote/'">>$filem
	echo "snapshot_name = 'snapshot_'+snapnum_str+'.hdf5'" >>$filem
    fi


    echo -e "\n" >>$filem

    echo "#where the files should go" >>$filem
    echo "PD_output_dir = '${model_dir_remote}/' ">>$filem
    echo "Auto_TF_file = 'snap'+snapnum_str+'.logical' ">>$filem
    echo "Auto_dustdens_file = 'snap'+snapnum_str+'.dustdens' ">>$filem

    echo -e "\n\n" >>$filem
    echo "#===============================================" >>$filem
    echo "#FILE I/O" >>$filem
    echo "#===============================================" >>$filem
    echo "inputfile = PD_output_dir+'/example.'+snapnum_str+'.rtin'" >>$filem
    echo "outputfile = PD_output_dir+'/example.'+snapnum_str+'.rtout'" >>$filem

    echo -e "\n\n" >>$filem
    echo "#===============================================" >>$filem
    echo "#GRID POSITIONS" >>$filem
    echo "#===============================================" >>$filem
    echo "x_cent = 0" >>$filem
    echo "y_cent = 0" >>$filem
    echo "z_cent = 0" >>$filem

done



echo "writing slurm submission master script file"
qsubfile="$model_dir/master.job"
rm -f $qsubfile
echo $qsubfile

echo "#! /bin/bash" >>$qsubfile
echo "SBATCH --job-name=$model_run_name" >>$qsubfile
echo "SBATCH --output=pd.master.o" >>$qsubfile
echo "SBATCH --error=pd.master.e" >>$qsubfile
echo "SBATCH --mail-type=ALL" >>$qsubfile
echo "SBATCH --mail-user=desika.narayanan@gmail.com" >>$qsubfile
echo "SBATCH --time=96:00:00" >>$qsubfile
echo "SBATCH --tasks-per-node=32">>$qsubvile
echo "SBATCH --nodes=$n_nodes">>$qsubfile
echo "SBATCH --mem-per-cpu=3800">>$qsubfile
echo "SBATCH --account=narayanan">>$qsubfile
echo "SBATCH --qos=narayanan-b">>$qsubfile
echo -e "\n">>$qsubfile
echo -e "\n" >>$qsubfile

echo "module purge">>$qsubfile
echo "module load git/1.9.0">>$qsubfile
echo "module load gsl/1.16">>$qsubfile
echo "module load gcc/5.2.0">>$qsubfile
echo "module load hdf5/1.8.16">>$qsubfile
echo "module load openmpi/1.10.2">>$qsubfile
echo -e "\n">>$qsubfile

echo "cd /home/desika.narayanan/pd/">>$qsubfile
for (( i=$startsnap; i<=$endsnap; i++ ))
do
    echo $i
    echo "python pd_front_end.py $model_dir_remote parameters_master model_$i  > $model_dir_remote/snap$i.txt">>$qsubfile

done
