#!/bin/bash
#SBATCH --job-name=pd_test
#SBATCH --output=pd_test.o
#SBATCH --error=pd_test.e
#SBATCH --mail-type=ALL
#SBATCH --mail-user=desika.narayanan@gmail.com
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4000
#SBATCH --account=narayanan
#SBATCH --qos=narayanan

module purge
module load gcc/7.3.0
module load openmpi/3.0.0
module load git
module load gsl
module load hdf5

cd /home/desika.narayanan/pd

python pd_front_end.py examples/gadget/mw_zoom/ parameters_master_401 test_model > LOG
